version: '3.3'

services:
  busybox:
    image: busybox
    volumes:
      - type: bind
        source : /datavol
        target : /data
        bind :
          propagation : rshared


    command: tail -f /etc/passwd
    deploy:
      mode: global
